version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "1221:5432"  # Используем порт 1221 для подключения извне
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: shorten-url-backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "9999:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --port 8000
      "

  celery:
    build: .
    container_name: celery_app
    command: ["celery", "-A", "src.tasks.tasks", "worker", "--loglevel=info", "--pool=solo"]
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis_app:6379/0

volumes:
  postgres_data:
