version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    command: -p 1221
    expose:
      - 1221
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  backend:
    build: .
    container_name: shorten-url-backend
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "9999:8000"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  celery:
    build: .
    container_name: celery_app
    command: ["celery", "-A", "src.tasks.tasks", "worker", "--loglevel=info", "--pool=solo"]
    depends_on:
      - redis

volumes:
  postgres_data:
